#!/bin/bash
## Shiver, Bash Hive Framework
## Licensed under the GNU GPLv3

##
# Initialize Shiver
#
function shiver()
{
    ## Check if Shiver is initialize or calling host script
    if [ "$ShiverInitialized" = true ]; then
        return 0;
    fi
    ShiverInitialized=true;

    ## Initialize Bashinator application variables
    setLibDir;
    export __ScriptFile=${0##*/} # thisscript.sh
    export __ScriptName=${__ScriptFile%.sh} # thisscript
    export __ScriptPath=${0%/*}; __ScriptPath=${__ScriptPath%/} # /path/to/this/script
    export __ScriptHost=$(hostname -f) # host.example.com
    export ShiverCallFile=$(readlink -f $__ScriptFile)

    ## Source Bashinator framework
    export __BashinatorConfig="${ShiverLib}/framework/bashinator/config.inc"
    export __BashinatorLibrary="${ShiverLib}/framework/bashinator.inc"
    if ! source "${__BashinatorConfig}"; then
        echo "!!! FATAL: failed to source bashinator config '${__BashinatorConfig}'" 1>&2
        exit 2
    fi
    if ! source "${__BashinatorLibrary}"; then
        echo "!!! FATAL: failed to source bashinator library '${__BashinatorLibrary}'" 1>&2
        exit 2
    fi

    ## Initialize Bashinator framework
    __boot
    __dispatch "${@}"
}

##
# Decorator for sourcing library files
#
function include()
{
    local ShiverInc="`echo $1 | sed -e 's@\.@/@g' -e 's@^shiver/@@'`.inc";
    local ShiverClassname=`basename "$ShiverInc" | cut -d. -f1`;
    local ShiverTestVar="Shiver"$ShiverClassname;

    # The following code will check:
    #    1. If there is a variable called __SHIVER_<CLASS>=1
    #        a. then: set the variable __SHIVER_SOURCE=false
    #        b. else: create it and set __SHIVER_SOURCE=true
    local ShiverTestExistence='if [ "$'$ShiverTestVar'" ]; then ShiverSourceExists=true; else ShiverSourceExists=false; '$ShiverTestVar'=1; fi';
    eval $ShiverTestExistence

    # --- source the include
    if [ "$ShiverSourceExists" = false ]; then
        __msg debug "Attempting to open $ShiverLib/$ShiverInc."
        __requireSource "$ShiverLib/$ShiverInc"
    fi
}

function setLibDir()
{
    ShiverLib=`caller 0 | cut -d ' ' -f 3 | sed -e s@/shiver@@`;
}

function __init()
{
    ## hive lib is expected
    include hive
    return 0;
}

function __main()
{
    # SOME HACKISH SHIT RIGHT HERE
    source $ShiverCallFile
    return 0;
}

##
# Run Shiver
#

shiver
